---
apiVersion: v1
kind: Namespace
metadata:
 creationTimestamp: null
 name: diplomado
spec: {}
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: env-global
data:
 APP_COLOR: blue
 DB_USER: root
 env-data: pruebaConfigMapenvdata
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: env-data
data:
 TZ: pruebaConfigMaptz
---
apiVersion: v1
kind: Secret
metadata:
 name: secret-env-pod
data:
 host: YWxndW5vLmNvbQ==
 DB_us: YWxndW5v
 DB_pass: c2VjcmV0bw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    commit: "578"
    affectedChannel: alguno
    owner: diplomado
    product: diplomado
    tierApp: Backend
    app: diplomado-re-v2-19-app
    tier: backend
    type: service
    automationTest: "false"
  name: diplomado-re-v2-19
  namespace: diplomado
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: diplomado-re-v2-19-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        commit: "578"
        affectedChannel: alguno
        owner: diplomado
        product: diplomado
        tierApp: Backend
        app: diplomado-re-v2-19-app
        tier: backend
        type: service
        automationTest: "false"
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      -
      #        labelSelector:
      #          matchExpressions:
      #            -
      #              key: app
      #              operator: In
      #              values:
      #                - diplomado-re-v2-19-app
      #        topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: PORT
          value: "8080"
        #- name: T_TOKEN
        #  valueFrom:
        #    secretKeyRef:
        #      name: tokensecret
        #      key: token
        #- name: T_AUTHENTICATION
        #  value: "TOKEN"
        #- name: T_TRUST_STORE
        #  value: "file:/vol-ms/pubcerts.ts"
        - name: MS_VERSION
          value: "re-v2-19"
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: "Wed Feb 03 10:39:52 CLST 2021"
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: env-data
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: CONTEXT_PATH
          value: "/v2.19"
        envFrom:
        - configMapRef:
            name: env-global
        livenessProbe:
          httpGet:
            path: /rest/mscovid/test?msg=testing
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 21
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /rest/mscovid/test?msg=testing
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        image: nicolashermosilla/devopsusach:latest
        imagePullPolicy: IfNotPresent
        name: diplomado-re-v2-19-node
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 608M
          limits:
            memory: 913M
            cpu: 1000m
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      imagePullSecrets:
      - name: prd
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: diplomado-re-v2-19-svc
  namespace: diplomado
spec:
  ports:
  - name: diplomado-re-v2-19-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: diplomado-re-v2-19-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
  selector:
    app: diplomado-re-v2-19-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: diplomado-re-v2-19
  namespace: diplomado
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: diplomado-re-v2-19
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplomado-re-v2-19-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: prototipo.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diplomado-re-v2-19
                port:
                  number: 80  

          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: hello-app
                port:
                  number: 8080  