---
apiVersion: v1
kind: Namespace
metadata:
 creationTimestamp: null
 name: diplomado
spec: {}
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: env-global
data:
 APP_COLOR: blue
 DB_USER: root
---
apiVersion: v1
kind: Secret
metadata:
 name: secret-env-pod
data:
 host: YWxndW5vLmNvbQ==
 DB_user: YWxndW5v
 DB_pass: c2VjcmV0bw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diplomado-re-v2-19-app
  name: diplomado-re-v2-19
  namespace: diplomado
spec:
  selector:
    matchLabels:
      app: diplomado-re-v2-19-app
  replicas: 2
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: diplomado-re-v2-19-app
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: MS_VERSION
          value: "re-v2-19"
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        livenessProbe:
          httpGet:
            path: /rest/mscovid/test?msg=testing
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 21
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /rest/mscovid/test?msg=testing
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        image: nicolashermosilla/devopsusach:latest
        imagePullPolicy: IfNotPresent
        name: diplomado-re-v2-19-node
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 608M
          limits:
            memory: 913M
            cpu: 1000m
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
      imagePullSecrets:
      - name: prd
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-volume
        emptyDir: {}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 30%
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  name: diplomado-re-v2-19-svc
  namespace: diplomado
spec:
  ports:
    - name: diplomado-re-v2-19-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: diplomado-re-v2-19-app
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: diplomado-re-v2-19
  namespace: diplomado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: diplomado-re-v2-19
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplomado-re-v2-19-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  backend:
    serviceName: other
    servicePort: 8080
spec:
  rules:
    - host: 35.239.221.195
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diplomado-re-v2-19
                port:
                  number: 8080  